order_show:
  path: /api/v1/orders/{id}
  controller: App\Controller\OrderController::showAction
  methods: [GET]

admin_customer_statistic:
  path: /api/v1/admin/customer/{id}/statistic
  controller: App\Controller\CustomerStatisticController::indexAction
  methods: [GET]
